# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/.Xil/Vivado-10704-Maria/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/ip/blk_mem_gen_0
    c:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.gen/sources_1/ip/blk_mem_gen_1
  } C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_vhdl -lib xil_defaultlib {
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/.Xil/Vivado-10704-Maria/realtime/blk_mem_gen_1_stub.vhdl
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/.Xil/Vivado-10704-Maria/realtime/blk_mem_gen_0_stub.vhdl
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/new/RGB_divider.vhd
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/new/SERPIENTE.vhd
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/new/botones_definitivo.vhd
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/new/comparador.vhd
      C:/Users/maria/Desktop/cont_digit.vhd
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/new/contador.vhd
      C:/Users/maria/Desktop/deco.vhd
      C:/Users/maria/Desktop/display_control_p1.vhd
      C:/Users/maria/Desktop/div_freq.vhd
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/new/draw.vhd
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/new/driverVGA.vhd
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/new/frec_pixel.vhd
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/new/gen_color.vhd
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/new/gestor.vhd
      C:/Users/maria/Desktop/reg_despl.vhd
      C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/Serpiente.srcs/sources_1/new/SERPIENTE_FULL.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top SERPIENTE_FULL
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/maria/Desktop/Serpiente_Display_movimientosorientados/Serpiente/.Xil/Vivado-10704-Maria/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
